In [1]:
import pandas as pd

In [2]:
folder = 'C:/Users/oryan/Documents/esac-project/manifests'

In [10]:
training_manifest = pd.read_csv(f'{folder}/gz-hubble-local-manifest.csv', index_col = 0)
full_manifest = pd.read_csv(f'C:/Users/oryan/Documents/zoobot/hubble-dataset-creation/data/gz_hubble_main.csv')

In [11]:
print(len(training_manifest))
print(len(full_manifest))

598
113705

In [13]:
training_manifest_rd = training_manifest[['zooniverse_id']]

In [22]:
full_manifest

,zooniverse_id,survey_id,Table,RA,DEC,Z_BEST,GZ_MU_I,imaging,correction_type,total_count,...,t17_clumps_symmetrical_a02_no_fraction,t17_clumps_symmetrical_a02_no_weighted_fraction,t17_clumps_symmetrical_total_count,t17_clumps_symmetrical_total_weight,t18_clumps_embedded_a01_yes_fraction,t18_clumps_embedded_a01_yes_weighted_fraction,t18_clumps_embedded_a02_no_fraction,t18_clumps_embedded_a02_no_weighted_fraction,t18_clumps_embedded_total_count,t18_clumps_embedded_total_weight
0,AGZ0007xmh,1,hubble,188.897318,62.200334,0.090,21.305056,GOODS-N-FULLDEPTH,2.0,40,...,0.333333,0.333333,3,3.0,0.666667,0.666667,0.333333,0.333333,3,3.0
1,AGZ0007xmi,4,hubble,188.901464,62.200705,999.000,23.121389,GOODS-N-FULLDEPTH,4.0,41,...,0.769231,0.769231,13,13.0,0.461538,0.461538,0.538462,0.538462,13,13.0
2,AGZ0007xmj,6,hubble,188.901567,62.201482,0.270,21.161961,GOODS-N-FULLDEPTH,2.0,40,...,0.500000,0.500000,6,6.0,0.666667,0.666667,0.333333,0.333333,6,6.0
3,AGZ0007xmk,13,hubble,188.905098,62.199973,999.000,23.676237,GOODS-N-FULLDEPTH,4.0,40,...,0.500000,0.500000,2,2.0,0.000000,0.000000,1.000000,1.000000,2,2.0
4,AGZ0007xml,16,hubble,188.906262,62.198074,999.000,21.821812,GOODS-N-FULLDEPTH,4.0,41,...,0.666667,0.666667,3,3.0,0.333333,0.333333,0.666667,0.666667,3,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113700,AHZ40008nu,90105528,hubble,52.873002,-27.580397,0.332,19.472644,GEMS,0.0,173,...,0.812000,0.812000,16,16.0,0.750000,0.750000,0.250000,0.250000,16,16.0
113701,AHZ40008nv,90105532,hubble,53.252911,-27.645872,999.000,19.235010,GEMS,4.0,87,...,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.0
113702,AHZ40008nw,90105589,hubble,52.982787,-27.578840,1.339,19.372154,GEMS,3.0,148,...,0.900000,0.900000,10,10.0,0.700000,0.700000,0.300000,0.300000,10,10.0
113703,AHZ40008nx,90107105,hubble,53.189682,-27.948248,999.000,19.059707,GEMS,4.0,31,...,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.0
113704,AHZ40008ny,90107114,hubble,53.190271,-27.948498,999.000,19.243291,GEMS,4.0,18,...,0.000000,0.000000,0,0.0,0.000000,0.000000,0.000000,0.000000,0,0.0

In [23]:
full_manifest_red = (
    full_manifest[['zooniverse_id','total_count','RA','DEC','t08_odd_feature_a06_merger_fraction','t08_odd_feature_a06_merger_weighted_fraction']]
    .rename(columns={'t08_odd_feature_a06_merger_fraction':'merger_fraction','t08_odd_feature_a06_merger_weighted_fraction':'weighted_merger_fraction'})
)

In [24]:
full_manifest_red

,zooniverse_id,total_count,RA,DEC,merger_fraction,weighted_merger_fraction
0,AGZ0007xmh,40,188.897318,62.200334,0.571429,0.571429
1,AGZ0007xmi,41,188.901464,62.200705,0.166667,0.166667
2,AGZ0007xmj,40,188.901567,62.201482,0.250000,0.250000
3,AGZ0007xmk,40,188.905098,62.199973,0.000000,0.000000
4,AGZ0007xml,41,188.906262,62.198074,0.000000,0.000000
...,...,...,...,...,...,...
113700,AHZ40008nu,173,52.873002,-27.580397,0.583000,0.583000
113701,AHZ40008nv,87,53.252911,-27.645872,0.000000,0.000000
113702,AHZ40008nw,148,52.982787,-27.578840,0.385000,0.415000
113703,AHZ40008nx,31,53.189682,-27.948248,0.000000,0.000000
113704,AHZ40008ny,18,53.190271,-27.948498,0.000000,0.000000

In [66]:
full_manifest_n = full_manifest_red.query('total_count > 50')
full_manifest_merg = full_manifest_n.query('merger_fraction >= 0.90')
full_manifest_no_merg = full_manifest_n.query('merger_fraction < 0.01')

In [67]:
full_manifest_merg

,zooniverse_id,total_count,RA,DEC,merger_fraction,weighted_merger_fraction
19466,AHZ10006eu,142,215.269748,53.029987,0.938,0.996
19500,AHZ10006fs,213,214.412091,52.493151,0.917,0.917
19520,AHZ10006gc,80,215.336288,53.124004,1.000,1.000
19571,AHZ10006hr,139,214.637148,52.694249,0.938,0.938
19592,AHZ10006ic,81,214.973274,52.833862,1.000,1.000
...,...,...,...,...,...,...
104616,AHZ2001tjt,104,150.085100,2.527799,1.000,1.000
107075,AHZ40001wa,124,53.070121,-27.999700,1.000,1.000
111573,AHZ40005d8,481,53.373838,-27.624108,1.000,1.000
111973,AHZ40005oc,410,53.200148,-27.613888,1.000,1.000
113639,AHZ40008m5,117,52.999558,-27.908689,1.000,1.000

In [68]:
full_manifest_no_merg

,zooniverse_id,total_count,RA,DEC,merger_fraction,weighted_merger_fraction
11159,AHZ1000003,728,214.130396,52.452309,0.0,0.0
11166,AHZ100000a,437,214.158930,52.458694,0.0,0.0
11173,AHZ100000h,563,214.330447,52.548667,0.0,0.0
11176,AHZ100000k,447,214.390325,52.524098,0.0,0.0
11187,AHZ100000v,501,214.421648,52.507669,0.0,0.0
...,...,...,...,...,...,...
113688,AHZ40008ni,150,53.140588,-27.603481,0.0,0.0
113691,AHZ40008nl,74,53.115410,-28.013901,0.0,0.0
113693,AHZ40008nn,83,52.922481,-27.912559,0.0,0.0
113696,AHZ40008nq,69,52.892251,-27.801323,0.0,0.0
113701,AHZ40008nv,87,53.252911,-27.645872,0.0,0.0

In [69]:
no_merg_sample_df = full_manifest_no_merg.sample(300)

In [70]:
validation_df = pd.concat([no_merg_sample_df, full_manifest_merg])

In [71]:
validation_set = training_manifest_rd.merge(validation_df, on='zooniverse_id',how='right',indicator=True).query('_merge != "both"')

In [72]:
validation_set

,zooniverse_id,total_count,RA,DEC,merger_fraction,weighted_merger_fraction,_merge
0,AHZ20014y0,186,150.617792,2.533808,0.0,0.0,right_only
1,AHZ400066w,372,52.932461,-27.630058,0.0,0.0,right_only
2,AHZ2001nce,173,149.510928,2.806075,0.0,0.0,right_only
3,AHZ2001oop,140,150.661058,1.709656,0.0,0.0,right_only
4,AHZ20008c0,191,150.743709,1.866699,0.0,0.0,right_only
...,...,...,...,...,...,...,...
633,AHZ2001tga,72,150.217657,2.333847,1.0,1.0,right_only
634,AHZ2001tgg,104,149.945407,2.461494,1.0,1.0,right_only
635,AHZ2001tjt,104,150.085100,2.527799,1.0,1.0,right_only
636,AHZ40001wa,124,53.070121,-27.999700,1.0,1.0,right_only
639,AHZ40008m5,117,52.999558,-27.908689,1.0,1.0,right_only

In [73]:
binary_validation_set = validation_set.assign(interaction = validation_set.weighted_merger_fraction.apply(lambda x: 1 if x >= 0.90 else 0))

In [76]:
binary_validation_set.interaction.value_counts()

0    308
1    108
Name: interaction, dtype: int64

In [79]:
export_df = binary_validation_set.drop(columns=['total_count','merger_fraction','weighted_merger_fraction','_merge'])

In [81]:
export_df.to_csv(f'{folder}/validation_set_manifest.csv')